ci: Create Windows Build script and Move poro.ico
LeagueOfPoro/CapsuleFarmerEvolved pull request #101
Opened 2023-02-08 23:09 UTC by auroraisluna

* Creates a Windows Build Script to allow building the exe in Windows
* Move the poro.ico in src/

2023-02-08 23:11 UTC, auroraisluna commented
Seems like GitHub added all my previous commits as well in the history.. interesting. Refer to 'file changes' for changes.

2023-02-08 23:37 UTC, hypixus requested changes

2023-02-08 23:37 UTC, hypixus commented on setup/windows.bat
> +@REM [BETA] v
I believe comments within .BAT files are made by simply using `REM <comment>`.

2023-02-08 23:37 UTC, hypixus commented on setup/windows.bat
> +python -m pipenv run pyinstaller -F --icon=src/poro.ico src/main.py --collect-all charset_normalizer -n CapsuleFarmerEvolved
This assumes default version on local machine is 3, which is not always true. Please use `python3`.

2023-02-08 23:37 UTC, hypixus commented on setup/windows.bat
> +set zipFileAnswer=no
How about using `true`/`false`? Batch does not understand boolean values, but that keeps the clarity in the longer run.

2023-02-08 23:37 UTC, hypixus commented on setup/windows.bat
> +echo [OK] Application build complete. You can find the application in the build directory.
The section with resetting the console window above is repeated a lot. How about throwing it into [a proper batch function?](http://www.trytoprogram.com/batch-file-functions/)

2023-02-08 23:50 UTC, auroraisluna commented on setup/windows.bat
> +python -m pipenv run pyinstaller -F --icon=src/poro.ico src/main.py --collect-all charset_normalizer -n CapsuleFarmerEvolved
There are Prerequisites to build the app (listed in the wiki), it is assumed these are followed. Advanced users modify the script as required.

2023-02-08 23:52 UTC, auroraisluna commented on setup/windows.bat
> +@REM [BETA] v
@REM and REM are the same commands, the @REM ensures the comment isn't echoed, regardless of the echo on/off state. As intended.

2023-02-09 00:00 UTC, auroraisluna commented on setup/windows.bat
> +set zipFileAnswer=no
Didn't think of using true/false at the time as like you mentioned batch does not read booleans, only 32bit ints or strings. Using `on/off` have the same meaning both linguistic and in variable type, I don't see how it adds more clarity.

2023-02-09 09:20 UTC, LeagueOfPoro commented
Let's move the `poro.ico` to `src/assets/poro.ico` to match #80

2023-02-09 17:08 UTC, hypixus approved these changes

2023-02-09 22:13 UTC, DjordyKoert commented
> Let's move the `poro.ico` to `src/assets/poro.ico` to match #80

I think `assets/poro.ico` is a better spot for these kind of  files. 
The banner image can also be placed here most likely.

2023-02-10 22:44 UTC, auroraisluna commented on setup/windows.bat
> +python -m pipenv run pyinstaller -F --icon=src/poro.ico src/main.py --collect-all charset_normalizer -n CapsuleFarmerEvolved
I will repeat my self more clearly this time:
The prerequisites demand for Python 3.10, if your system has different versions installed, you are not following the prerequisites, and therefore you will need to edit the script on your own to match them.

This is an advanced script aimed at advanced users. 
If said advanced user doesn't know the different Python commands in their system, that's on them. 

And by the way, Python3 isn't a default either. Assuming the mentioned points didn't matter, it would still not work for a lot of advanced users. 

TLDR; Useless back-and-forth for a fix each advanced user can apply as required up to their current installation.

2023-02-11 04:38 UTC, auroraisluna commented
Will not be moving the banner. It is not an asset of the app.

2023-04-16 11:14 UTC, closed without merging