fix: Show correct time until next match
LeagueOfPoro/CapsuleFarmerEvolved pull request #147
Opened 2023-02-15 00:42 UTC by MJ-GH

Fixes #124 

## Summary of Changes

Properly displays time until next match in the Live Matches column.

## Additional context

Discord username (if different from GitHub): Frozty

## Testing instructions

Sometimes it won't be able to set a time because the json response is not up to date. Usually happens right as a match goes live and the event will show 'state': 'unstarted' when its actually live(should be 'state': 'inProgress'). The issue resolves itself as the data is updated. It gave me a headache during testing, so just keep it in mind.

## How to download the PR for testing

### Using [GitHub CLI](https://cli.github.com/)
1. Clone this PR
2. Run `gh pr checkout 124` (Requires [GitHub CLI](https://cli.github.com/)) 
3. Follow the [Advanced Installation Guides from the Wiki](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki)

### Using regular GIT
1. Fetch the PR `git fetch origin pull/<PR_NUMBER>/head:<LOCAL_BRANCH_NAME>` (e.g. `git fetch origin pull/110/head:notif`)
2. Checkout the branch `git checkout <LOCAL_BRANCH_NAME>` (e.g. `git checkout notif`)
3. Follow the [Advanced Installation Guides from the Wiki](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki)

2023-02-15 10:51 UTC, LeagueOfPoro commented
Can someone test it please?

2023-02-15 15:04 UTC, Nub01 commented
Seems to be working, I'm in PST, and next stream/game is in 56 mins,

2023-02-16 18:01 UTC, MJ-GH commented
[2839e5b](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/pull/147/commits/2839e5ba58ea62a109a8c29179cb44ca669d50f3) fixes a rare edge case that happened this morning, where some matches were supposed to have started, but they didn't for some reason. My guess is delayed or cancellation. In case it happens again this commit will change the Live matches column to:
![billede](https://user-images.githubusercontent.com/39399890/219448650-341ea711-51a2-4bb9-90e4-62ad63dfac88.png)

2023-02-18 10:38 UTC, auroraisluna approved these changes
LGTM till latest commit. I am unsure if that's going to cause issues. Haven't tested that part either.

2023-02-19 15:02 UTC, LeagueOfPoro requested changes
Idea: instead of the weird fix for a delayed match what about changing the message to something like "Up next: LEC at 19:00"

2023-02-20 00:13 UTC, MJ-GH commented on src/DataProviderThread.py
> +                        minutes, seconds = divmod(remainder, 60)
fixed with commit [388c75f](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/pull/147/commits/388c75fdee3fd3e4f0106856a73bbbb3547ed5b8)

2023-02-20 00:13 UTC, MJ-GH commented on src/DataProviderThread.py
> +                                    minutes, seconds = divmod(remainder, 60)
fixed with commit [388c75f](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/pull/147/commits/388c75fdee3fd3e4f0106856a73bbbb3547ed5b8)

2023-02-20 00:47 UTC, MJ-GH commented
> Idea: instead of the weird fix for a delayed match what about changing the message to something like "Up next: LEC at 19:00"

We'd be assuming everyone is in the same timezeone, if we write "19:00", that's why we calculate the time until the next match starts.
So the question is what do you want me to do with the else clause: 
```python
                    else:  # We're past the startTime due to delay or cancellation i'm guessing
                        niceStartTime = datetime.strftime(self.startTime, '%H:%M')
                        self.sharedData.setTimeUntilNextMatch(f"{event['league']['name']} should've started at {niceStartTime} but hasn't.")
                        for nextEvent in events:  # Looping again to find next match that weren't supposed to have started already
                            if nextEvent["state"] == "unstarted":
                                if self._isStartTimeLater(nextEvent["startTime"]):
                                    days, hours, minutes = self._calculateTime()
                                    self.sharedData.addTimeUntilNextMatch(
                                        f"Next in {days}d {hours}h" if days else f'Next in {hours}h {minutes}m')
                                    break
```
Thing is, if the if statement fails and we calculate time, then it will return -1 days. I could just have it say "None - Couldn't determine when next match is", like in my initial commit, or we loop through the events again like it does now, and calculate time once more. And then remove the "LEC should've started at 19:00" part. I can see why it's a weird fix for such a rare case, but it's up to you.

2023-02-20 01:07 UTC, Skribb11es commented
Couldn't you just use the system time + the time until the next game to format it correctly according to their timezone? Also shouldn't riot's APIs be returning the timezone-corrected start times anyhow?

2023-02-20 01:20 UTC, Nub01 commented
> Couldn't you just use the system time + the time until the next game to format it correctly according to their timezone? Also shouldn't riot's APIs be returning the timezone-corrected start times anyhow?

this is what wiflow tried doing isn't it?

2023-02-20 10:11 UTC, MJ-GH commented
> Couldn't you just use the system time + the time until the next game to format it correctly according to their timezone? Also shouldn't riot's APIs be returning the timezone-corrected start times anyhow?

Riot's api doesn't do that, the start times are all UTC+0.

2023-02-20 23:29 UTC, MJ-GH commented
> Idea: instead of the weird fix for a delayed match what about changing the message to something like "Up next: LEC at 19:00"

commit [c29a502](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/pull/147/commits/c29a502a81865a45c98432093cb0027641a76df8) makes it print a timezone-correct starttime no matter which timezone you're in, in the format you suggested. 

@Skribb11es showed me on discord how easy that was. Thanks!

I also got rid of the weird fix with the nested for loop. 

I'd like it tested in different timezones than mine(UTC+1) and if you don't want to wait for a real scanario, you can test this commit by adding this line to the end of the try clause between line 104 and 105.
`
print(self.sharedData.getTimeUntilNextMatch())
`
It should print this in the terminal with starttime in your timezone: 
![image](https://user-images.githubusercontent.com/39399890/220212220-f81567bb-728a-4891-87d8-d7704d0ade65.png)
Check if the time matches the next match starttime on the schedule here: https://lolesports.com/schedule

2023-02-21 01:49 UTC, Skribb11es commented
LGTM, times match up with the correct timestamp for UTC-5, well done.

2023-02-21 11:08 UTC, DeadSpc commented
![image](https://user-images.githubusercontent.com/125975262/220328647-1ed8ec9f-7b0d-4d92-a1da-bd2519b958bf.png)

help what should i do?

2023-02-21 11:59 UTC, DeadSpc commented
![image](https://user-images.githubusercontent.com/125975262/220338933-4198b6c6-7dba-4d67-81a6-bc5aa673063e.png)
help

2023-02-21 12:05 UTC, auroraisluna commented
> ![image](https://user-images.githubusercontent.com/125975262/220338933-4198b6c6-7dba-4d67-81a6-bc5aa673063e.png) help

You need to follow the advanced installation guide as the PR description shows, to test it locally.

2023-02-21 12:59 UTC, KitsumyFox commented
> ![image](https://user-images.githubusercontent.com/125975262/220338933-4198b6c6-7dba-4d67-81a6-bc5aa673063e.png) help

I think you just need _**pipenv install**_

2023-02-22 08:44 UTC, merged