fix:
LeagueOfPoro/CapsuleFarmerEvolved pull request #156
Opened 2023-02-16 23:20 UTC by Skribb11es

Fixes #[issue_no]

## Summary of Changes

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for testing

### Using [GitHub CLI](https://cli.github.com/)
1. Clone this PR
2. Run `gh pr checkout 124` (Requires [GitHub CLI](https://cli.github.com/)) 
3. Follow the [Advanced Installation Guides from the Wiki](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki)

### Using regular GIT
1. Fetch the PR `git fetch origin pull/<PR_NUMBER>/head:<LOCAL_BRANCH_NAME>` (e.g. `git fetch origin pull/110/head:notif`)
2. Checkout the branch `git checkout <LOCAL_BRANCH_NAME>` (e.g. `git checkout notif`)
3. Follow the [Advanced Installation Guides from the Wiki](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki)

2023-02-16 23:21 UTC, Skribb11es commented
Really had to make 3 PR's and finally have Rusty make a new branch just for the DIFF to be correct, ffs

2023-02-16 23:48 UTC, Penguax commented
Lots of testing talk in #dev channel on Discord. 

# SKIP images for summary

Below is some testing with the fixes in this PR 
### 1.Both Farmers are identical except for `accountname` 
![image](https://user-images.githubusercontent.com/65429733/219512943-b5a27787-8f7b-4109-baa7-1358279f28ff.png)
### 2. Changed `GeoLocation` on the RIGHT farmer
![image](https://user-images.githubusercontent.com/65429733/219512813-b8abed1f-3dfb-4c2c-953f-1e6ea397a735.png)
### 3. Changed `GeoLocation` + `Referer` fix changes on RIGHT farmer.
![image](https://user-images.githubusercontent.com/65429733/219513065-94def60b-d629-431b-bb5b-1c254ae08f3b.png)
### 4. Changed ONLY `Referer` on RIGHT farmer. 
![image](https://user-images.githubusercontent.com/65429733/219513130-82ee744c-a053-448c-bc1f-faf19274777d.png)

Summary: 
Changing geolocation didn't affect the login / "api" status of the farmer, however changing `Referer` did, I can also confirm ive already gotten 3 drops using the fix. 

*Note* 
Changing `Referrer` -> `Referer`, also fixes this issue, however completely removing the referer lines also negates the issue of having to implement a fix to flip flop between the two spellings in the code to satisfy the wanted request headers.

2023-02-18 10:34 UTC, auroraisluna commented
Please also update your PR to include the standard PR template: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2023-02-18 19:10 UTC, Skribb11es commented
> Please also update your PR to include the standard PR template: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/blob/master/.github/PULL_REQUEST_TEMPLATE.md

As is, it includes everything from the "standard PR template" just using different wording, it's even laid out in the exact same order.

2023-02-18 22:52 UTC, auroraisluna commented
> > Please also update your PR to include the standard PR template: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/blob/master/.github/PULL_REQUEST_TEMPLATE.md
> 
> As is, it includes everything from the "standard PR template" just using different wording, it's even laid out in the exact same order.

The template is there to be followed to the letter. Please update your PR description to use the template. Suggesting moving the first content of your current under "Summary", everything else under additional context 👍
Key Missing Sections: 
- [ ] 'Testing instructions' section
- [ ] 'How to download the PR for testing' required section 

Thanks.

2023-02-19 14:28 UTC, LeagueOfPoro requested changes

2023-02-19 14:28 UTC, LeagueOfPoro commented on src/main.py
> +CURRENT_VERSION = 1.33
Don't change the version

2023-02-19 14:28 UTC, LeagueOfPoro commented on src/Browser.py
> +                    "https://account.rewards.lolesports.com/v1/session/token", headers={"Origin": "https://lolesports.com", self.ref: "https://lolesports.com"})
Don't create a nested function. Looking at @Penguax testing, is the function even necessary? Could we only remove te Referer completely?

2023-02-19 14:28 UTC, LeagueOfPoro commented on src/main.py
> +    print(f"*   Thank you for using Capsule Farmer Evolved v{str(CURRENT_VERSION)}!    *")
the str is not needed

2023-02-19 14:30 UTC, LeagueOfPoro commented
I currently don't have access to pc to test it. It looks like @Penguax did. Can we just remove referer everywhere?

2023-02-19 20:47 UTC, Skribb11es commented on src/main.py
> +    print(f"*   Thank you for using Capsule Farmer Evolved v{str(CURRENT_VERSION)}!    *")
resolved the coloring issue seen with the version number being half white and half blue in the console.

2023-02-19 20:48 UTC, Skribb11es commented on src/Browser.py
> +                    "https://account.rewards.lolesports.com/v1/session/token", headers={"Origin": "https://lolesports.com", self.ref: "https://lolesports.com"})
Explained in discord. #capsule-farmer-dev [here](https://discord.com/channels/493691955184926720/1071031553460817990/1076948085827194890)

2023-02-19 20:58 UTC, Skribb11es commented
> It looks like @Penguax did. I tried it and I think we just remove referer everywhere.

explained via discord, and also removed the nested func.

2023-02-19 21:18 UTC, Penguax commented
removing `referer` everywhere caused some login issues for some users/ when adding new accounts afterwords. when only removing it from the `watch` area it worked fine for them, but there's no knowing if in the future they also start denying watch packets with missing referer headers.

2023-02-19 21:34 UTC, Skribb11es commented
Well more specifically adding to the above comment, Riot's API servers switch their headers back and forth from time to time, presumably based on load, as I said in the PR's initial comment. However, this does also mean that each individual API has its own headers, which does complicate things but is also pretty easy to catch if you simply add an if elif statement as I did for "v 1.33".

2023-02-22 09:20 UTC, LeagueOfPoro approved these changes

2023-02-22 09:20 UTC, merged