Added Drop and 2FA Notifications and Toasts
LeagueOfPoro/CapsuleFarmerEvolved pull request #80
Opened 2023-02-07 19:25 UTC by Mazen-Ghaleb

As previously mentioned in #75 , It was required to make the cross-platform to use custom sounds. I have satisfied that using different library known as notifypy. However, this library makes toasts in addition to sound in the same notification.

2023-02-07 20:40 UTC, auroraisluna commented
If I understand this, you are required to enable toasts to also have a sound. Is it possible to only have a toast without the audio or are both required?

Also I recommend making this entire notification service its own file for easier maintenance (and for future use from other places)

2023-02-07 20:55 UTC, Mazen-Ghaleb commented
> 

It is possible to have toast without audio by simple removing the following line:
`notification.audio = "./sounds/NotificationSound.wav"`
More examples of the library can be found [here](https://morioh.com/p/c31b69590849),  so using this library requires it to be a toast, but it is not a must to have a sound. 

I will try to do the notification file (Notification.py) asap

2023-02-07 21:05 UTC, auroraisluna commented
> More examples of the library can be found [here](https://morioh.com/p/c31b69590849). Using this library requires it to be a toast, but it is not a must to have a sound.

Alright. Let's make it also configurable as shown here: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Configuration (bottom)

2023-02-07 21:08 UTC, Mazen-Ghaleb commented
> > More examples of the library can be found [here](https://morioh.com/p/c31b69590849). Using this library requires it to be a toast, but it is not a must to have a sound.
> 
> Alright. Let's make it also configurable as shown here: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Configuration (bottom)

Using notify, it has to be toast, there can't be audio without toast but we can make condition if toast only or toast and sound then use notify else if sound only then use beepy. What do you think about this suggestion ?

2023-02-07 21:12 UTC, auroraisluna commented
> > > More examples of the library can be found [here](https://morioh.com/p/c31b69590849). Using this library requires it to be a toast, but it is not a must to have a sound.
> > 
> > 
> > Alright. Let's make it also configurable as shown here: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Configuration (bottom)
> 
> Using notify, it has to be toast, there can't be audio without toast but we can make condition if toast only or toast and sound then use notify else if sound only then use beepy. What do you think about this suggestion ?

It's fine if you have to enable toasts for the sounds. Better not bloat with two modules for just one tiny extra feature.

2023-02-07 21:13 UTC, wiflow commented
This will probably make it only work for Windows though. Unless it has cross-platform, and has os detection itself.

2023-02-07 21:14 UTC, Mazen-Ghaleb commented
> This will probably make it only work for Windows though. Unless it has cross-platform, and has os detection itself.

Beepy is cross-platform too as mentioned in #75

2023-02-08 00:22 UTC, Mazen-Ghaleb commented
> > More examples of the library can be found [here](https://morioh.com/p/c31b69590849). Using this library requires it to be a toast, but it is not a must to have a sound.
> 
> Alright. Let's make it also configurable as shown here: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Configuration (bottom)

I have tried to implement and satisfy the configuration and tested on Windos onStart, onFault, and Drops. I didn't test 2FA yet or other platforms. I used soundaudio for sound only but dont know if it supports cross-platform

2023-02-08 00:37 UTC, auroraisluna requested changes

2023-02-08 00:37 UTC, auroraisluna commented on config/config.yaml
> +notificationOnStart: True
Do not include these as they are optional

2023-02-08 00:38 UTC, Mazen-Ghaleb commented on config/config.yaml
> +notificationOnStart: True
Okay 👍

2023-02-08 13:15 UTC, LeagueOfPoro commented on src/Notifications.py
> +        self.soundPath = config.get("soundPath","../defaultNotificationSound.wav")
This default value will be a problem in the flat EXE version.

2023-02-08 13:18 UTC, LeagueOfPoro commented on src/Notifications.py
> +        self.soundPath = config.get("soundPath","../defaultNotificationSound.wav")
I suggest adding `src/assets/ ` folder

2023-02-08 13:35 UTC, Mazen-Ghaleb commented on src/Notifications.py
> +        self.soundPath = config.get("soundPath","../defaultNotificationSound.wav")
> I suggest adding `src/assets/ ` folder

Done 👍

2023-02-08 13:41 UTC, DjordyKoert commented on src/Notifications.py
> +        self.soundPath = config.get("soundPath","../defaultNotificationSound.wav")
Shouldn't this be `assets/`? instead of `src/assets/`

2023-02-08 13:55 UTC, LeagueOfPoro commented on src/Notifications.py
> +        self.soundPath = config.get("soundPath","../defaultNotificationSound.wav")
> Shouldn't this be `assets/`? instead of `src/assets/`

Not sure about the correct Python way, but for example in Angular it is in `src/assets`. It doesn't matter though because if we put it to root, it will create issues with the exe anyway.

2023-02-08 16:20 UTC, bblxssm commented
LGTM

2023-02-09 10:11 UTC, LeagueOfPoro commented on src/Config.py
> +                self.notificationManager = NotificationManager(config)
Pass the Config class not the text of the config file.

2023-02-09 10:11 UTC, LeagueOfPoro commented on src/Notifications.py
> +        self.soundOnFault = config.get("soundOnFault", False)
Don't extract the values from the config file here. Save them inside the Config class and then get it from there.

2023-02-09 10:31 UTC, Mazen-Ghaleb commented on src/Notifications.py
> +        self.soundOnFault = config.get("soundOnFault", False)
> Don't extract the values from the config file here. Save them inside the Config class and then get it from there.

I had implemented it like that in the begining with getters but was told to do it like this to be more independent, anyways I will implement it with getters asap

2023-02-09 10:54 UTC, LeagueOfPoro commented on src/Notifications.py
> +        self.soundOnFault = config.get("soundOnFault", False)
I didn't notice someone suggested it this way. Ny reasoning is that the Config class works as an abstraction layer between functions that use the values and the actual file.

2023-02-09 11:04 UTC, Mazen-Ghaleb commented on src/Notifications.py
> +        self.soundOnFault = config.get("soundOnFault", False)
> I didn't notice someone suggested it this way. Ny reasoning is that the Config class works as an abstraction layer between functions that use the values and the actual file.

I agree but I was following the suggestions. Anyways, I have implemented it and pushed. I tested onStart, onFault and onDrop on Windows 11.

2023-02-09 12:09 UTC, LeagueOfPoro commented on src/Notifications.py
> +        self.soundOnFault = config.get("soundOnFault", False)
Thank you

2023-02-09 12:11 UTC, LeagueOfPoro commented
Please resolve the conflicts and press Ready to review whenever it becomes ready for merge.

2023-02-09 12:50 UTC, LeagueOfPoro commented
Was this close intentional?

2023-02-09 13:10 UTC, Mazen-Ghaleb commented
> 

No

2023-02-09 13:12 UTC, Mazen-Ghaleb commented
>

2023-02-09 16:46 UTC, LeagueOfPoro commented
Just a few more things and we are ready to merge:
- If the required files are not found, the thread just "quietly" crashes with no error shown on the screen. (Code below)
- Add enable all sound and enable all notifications options. (Code below)

NotificationManager:
```python
from rich import print

...

def __init__(self, config: Config):
        """
        Initialize the NotificationManager class

        :param config: Config class object
        """
        self.notificationOnStart = config.getNotificationOnStart()     
        self.notificationOn2FA = config.getNotificationOn2FA()
        self.notificationOnDrop = config.getNotificationOnDrop()
        self.notificationOnFault = config.getNotificationOnFault()

        self.soundPath = config.getSoundPath() 
        self.soundOnStart = config.getSoundOnStart()
        self.soundOn2FA = config.getSoundOn2FA()
        self.soundOnDrop = config.getSoundOnDrop()
        self.soundOnFault = config.getSoundOnFault()

        if not (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():
            print(f"[red]CRITICAL ERROR: The notification sound file cannot be found at {self.soundPath}\nYou can specify a different file by 'soundPath: \"/path/to/file.wav\"' in config.")
            print("Press any key to exit...")
            input()
            raise FileNotFoundError(self.soundPath)

```

Config:
```python
                if config.get("notificationAll", False):
                    self.notificationOnStart = True
                    self.notificationOn2FA = True
                    self.notificationOnDrop = True
                    self.notificationOnFault = True
                else:
                    self.notificationOnStart = config.get("notificationOnStart", False)
                    self.notificationOn2FA = config.get("notificationOn2FA", False)
                    self.notificationOnDrop = config.get("notificationOnDrop", False)
                    self.notificationOnFault = config.get("notificationOnFault", False)
                
                self.soundPath = config.get("soundPath","./assets/defaultNotificationSound.wav")
                if config.get("soundAll", False):
                    self.soundOnStart = True
                    self.soundOn2FA = True
                    self.soundOnDrop = True 
                    self.soundOnFault = True          
                else:
                    self.soundOnStart = config.get("soundOnStart", False)
                    self.soundOn2FA = config.get("soundOn2FA", False)
                    self.soundOnDrop = config.get("soundOnDrop", False)
                    self.soundOnFault = config.get("soundOnFault", False)
```

2023-02-09 16:48 UTC, LeagueOfPoro commented on src/Stats.py
> +    def update(self, notificationManager: NotificationManager, accountName: str, newDrops: int = 0, liveMatches: str = ""):
Pass the NotificationManager in __init__ instead of update.

2023-02-09 16:56 UTC, Mazen-Ghaleb commented
> Just a few more things and we are ready to merge:
> 
> * If the required files are not found, the thread just "quietly" crashes with no error shown on the screen. (Code below)
> * Add enable all sound and enable all notifications options. (Code below)
> 
> NotificationManager:
> 
> ```python
> from rich import print
> 
> ...
> 
> def __init__(self, config: Config):
>         """
>         Initialize the NotificationManager class
> 
>         :param config: Config class object
>         """
>         self.notificationOnStart = config.getNotificationOnStart()     
>         self.notificationOn2FA = config.getNotificationOn2FA()
>         self.notificationOnDrop = config.getNotificationOnDrop()
>         self.notificationOnFault = config.getNotificationOnFault()
> 
>         self.soundPath = config.getSoundPath() 
>         self.soundOnStart = config.getSoundOnStart()
>         self.soundOn2FA = config.getSoundOn2FA()
>         self.soundOnDrop = config.getSoundOnDrop()
>         self.soundOnFault = config.getSoundOnFault()
> 
>         if not (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():
>             print(f"[red]CRITICAL ERROR: The notification sound file cannot be found at {self.soundPath}\nYou can specify a different file by 'soundPath: \"/path/to/file.wav\"' in config.")
>             print("Press any key to exit...")
>             input()
>             raise FileNotFoundError(self.soundPath)
> ```
> 
> Config:
> 
> ```python
>                 if config.get("notificationAll", False):
>                     self.notificationOnStart = True
>                     self.notificationOn2FA = True
>                     self.notificationOnDrop = True
>                     self.notificationOnFault = True
>                 else:
>                     self.notificationOnStart = config.get("notificationOnStart", False)
>                     self.notificationOn2FA = config.get("notificationOn2FA", False)
>                     self.notificationOnDrop = config.get("notificationOnDrop", False)
>                     self.notificationOnFault = config.get("notificationOnFault", False)
>                 
>                 self.soundPath = config.get("soundPath","./assets/defaultNotificationSound.wav")
>                 if config.get("soundAll", False):
>                     self.soundOnStart = True
>                     self.soundOn2FA = True
>                     self.soundOnDrop = True 
>                     self.soundOnFault = True          
>                 else:
>                     self.soundOnStart = config.get("soundOnStart", False)
>                     self.soundOn2FA = config.get("soundOn2FA", False)
>                     self.soundOnDrop = config.get("soundOnDrop", False)
>                     self.soundOnFault = config.get("soundOnFault", False)
> ```

Shouldn't the following if condition not have the first "not ?
`if not (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():`

2023-02-09 16:58 UTC, LeagueOfPoro commented
> Shouldn't the following if condition not have the first "not ?
if not (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():

Oh, yes, good catch. I had it somewhere else and then moved it. This should work: 
`if (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():`

2023-02-09 17:19 UTC, Mazen-Ghaleb commented
> > Shouldn't the following if condition not have the first "not ?
> > if not (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():
> 
> Oh, yes, good catch. I had it somewhere else and then moved it. This should work: `if (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():`

Also shouldn't the condition be in config.py after reading the path not in notifications.py cause this way it will be quicker?

2023-02-09 17:51 UTC, Mazen-Ghaleb commented
I have made the changes, but couldn't push because somehow the repository (the forked one) got deleted when I pressed "ready for review". Therefore, whenever I try to push the new changes, I get the following error:
![image](https://user-images.githubusercontent.com/86268979/217891207-4e2da12e-f19f-4fdd-8676-0c34de5afb63.png)

I have tried to retrieve it from deleted repositories and apparently I have support to restore them because it is a fork
![image](https://user-images.githubusercontent.com/86268979/217891963-c837c4a3-dad4-4962-a0b0-beffc243fc0d.png)

I am puzzled by how this happened and why I can't do updates but thankfully that the work still exists here eventhough it was deleted somehow.

I have even tried to clone this repository and checkout on this PR (#80) then do the change and publish but was met with the following error at publishing 
![image](https://user-images.githubusercontent.com/86268979/217896112-117331dc-f927-406e-9e60-f131d196cf9f.png)

I guess this can be fixed in next PR, or I can send you changes I made then you guys can push because I don't have authroity to push it anymore or lastly maybe restore my fork :( .

2023-02-09 18:19 UTC, LeagueOfPoro commented
> > > Shouldn't the following if condition not have the first "not ?
> > > if not (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():
> > 
> > 
> > Oh, yes, good catch. I had it somewhere else and then moved it. This should work: `if (self.soundOnStart or self.soundOn2FA or self.soundOnDrop or self.soundOnFault) and not Path(self.soundPath).exists():`
> 
> Also shouldn't the condition be in config.py after reading the path not in notifications.py cause this way it will be quicker?

That was my original thought, but then we would need a different exception to provide the correct error message. Possibly something like `AssetNotFoundException`? Feel free to do whichever you like more.

2023-02-09 18:21 UTC, LeagueOfPoro commented
> I have made the changes, but couldn't push because somehow the repository (the forked one) got deleted when I pressed "ready for review". Therefore, whenever I try to push the new changes, I get the following error: ![image](https://user-images.githubusercontent.com/86268979/217891207-4e2da12e-f19f-4fdd-8676-0c34de5afb63.png)
> 
> I have tried to retrieve it from deleted repositories and apparently I have to contact support to restore it because it was a fork ![image](https://user-images.githubusercontent.com/86268979/217891963-c837c4a3-dad4-4962-a0b0-beffc243fc0d.png)
> 
> I am puzzled by how this happened and why I can't do updates but thankfully that the work still exists here eventhough it was deleted somehow.
> 
> I have even tried to clone this repository and checkout on this PR (#80) then do the change and publish but was met with the following error at publishing ![image](https://user-images.githubusercontent.com/86268979/217896112-117331dc-f927-406e-9e60-f131d196cf9f.png)
> 
> I guess this can be fixed in next PR, or I can send you changes I made then you guys can push because I don't have authroity to push it anymore or lastly maybe restore my fork 😢 . If I refork, will it fix it? 🤔

If you still have the changes locally, you should be able to create a new branch and new PR.

2023-02-09 18:23 UTC, Mazen-Ghaleb commented
> 

It still existed after that because I was able to push the merge, but after the merge when I applied ready for review. The repo disappeared.

2023-02-09 19:04 UTC, LeagueOfPoro commented
> 

Ok, let me know when we can do the final check

2023-02-09 21:54 UTC, DjordyKoert commented
@Mazen-Ghaleb I think this pr can be closed now, since all changes are now in pr #110

2023-02-10 08:55 UTC, closed without merging