Banner + readme changes
LeagueOfPoro/CapsuleFarmerEvolved pull request #83
Opened 2023-02-07 20:45 UTC by Penguax

Added a banner to the top replacing `# Capsule Farmer Evolved` But still contains it as a fallback if image doesn't load. 
Added img.shields icons for repo, linked to leagueofporo already. 
Added readme contents table.
Moved discord and yt links up. Inside of Community Section
Organized Installation and added additional wording for windows installation. 
Corrected `--rm` in docker commands
Added disclaimer at bottom.

2023-02-07 21:00 UTC, auroraisluna requested changes

2023-02-07 21:00 UTC, auroraisluna commented on README.md
> -docker run -it --rm --restart unless-stopped -d -v /path/to/config.yaml:/config/config.yaml  capsulefarmerevolved
Why remove the rm?

2023-02-07 21:16 UTC, auroraisluna commented
Also, forgot to mention, remove the installation guides etc, and link the quickstart to the wiki. As well as the advanced installation/build your self, link to the wiki as well :)

2023-02-07 22:15 UTC, Penguax commented
[Advanced Installation For Linux.md](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10679816/Advanced.Installation.For.Linux.md)
[Advanced Installation for Windows.md](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10679817/Advanced.Installation.for.Windows.md)
[Advanced Installation for Docker.md](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10679818/Advanced.Installation.for.Docker.md)

@auroraisluna 
Wiki pages in markdown attached, Readme updated to remove the guides and link to wiki, google tv is included with the correct link if the PR is merged.

2023-02-07 22:42 UTC, Penguax commented
[Advanced Installation for Synology Docker.md](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10679981/Advanced.Installation.for.Synology.Docker.md)
[Advanced Installation for Windows.md](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10679982/Advanced.Installation.for.Windows.md)
[Advanced Installation for Docker.md](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10679983/Advanced.Installation.for.Docker.md)
[Advanced Installation for Linux.md](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10679984/Advanced.Installation.for.Linux.md)


Configuration link was done incorrectly, is now hard linked to wiki link for leagueofporo/capsulefarmerevolved. 

Added Synology Docker readme

2023-02-07 23:27 UTC, auroraisluna approved these changes
LGTM

2023-02-07 23:28 UTC, auroraisluna commented
Wiki changes are being pushed as we speak. Wait for @LeagueOfPoro to accept and merge.

2023-02-08 08:09 UTC, LeagueOfPoro commented
Looks good, merging

2023-02-08 08:09 UTC, merged